### ISSUE TITLE
Health Checks run twice

### ISSUE THREAD

**Issue by crperez5** [thedillonb/Owin.HealthCheck#1]
Hi there, 

just to report that at line 72 in HealthCheckMiddleware.cs, where you invoke .Result method, this causes the Health Checks to run all over again. However allTasks variable is already referencing the resolved Task, you could make use of that. 

We have noticed this because of low performance. 

Regards, Cristian.

**Comment by thedillonb** [comment]
Holy cow. Great catch. I can't believe I missed that. I've published a new version (1.0.22)
